# Comment to a new issue.
issuesOpened: >
  Thank you for raising a issue.<br>

  Please keep in mind that this project is not actively maintained. This project only handles webOS specific player components. Everything else needs to be raised in the upstream repository anyways: https://github.com/fgl27/SmartTwitchTV/issues

pullRequestOpened: >
  Thank your for raising your pull request.

  Please keep in mind that this project is not actively maintained. This project only handles webOS specific player components. Everything else needs to be raised in the upstream repository anyways: https://github.com/fgl27/SmartTwitchTV/pulls

